### ISSUE TITLE
Possible issue

### ISSUE THREAD

**Issue by Mooslemike** [f90/RaidInviteClassic#1]
First, love this, it's awesome! 
Second, codewords aren't working correctly. I tried multiple settings and could never get it to auto invite a guildie that whispered me whether they were on the list or not, whether invites were started or not. If you need help testing I am Gad on Atiesh-US.

**Comment by f90** [comment]
@Mooslemike Hey, thanks for the feedback :) Are you available at about 23:00 GMT tonight? Then we can meet up and debug the issue. Thanks!

**Comment by Mooslemike** [comment]
Yes, I’ll be free. My Discord is Gad#0451

**Comment by f90** [comment]
Seems to have been resolved in v0.3, so closing this for now.
