### ISSUE TITLE
Add support for Discord Raid-Helper event exports as import string.

### ISSUE THREAD

**Issue by Witnessthis** [f90/RaidInviteClassic#14]
When creating a Raid-Helper event in discord you can use "!print <Event ID>" to export your signups as a CSV. The output of this command is what I want to add as an import string to RIC.

I made an ugly hack myself but I doubt anyone wants to merge my version. so  I'll use it myself for now and hopefully you decide to add official support for Raid-Helper!

Kind Regards,

Witnessthis

**Comment by f90** [comment]
Hey, sounds like a good idea to make Raid Invite Classic understand such CSV as input. Could you attach some example CSV file here please? Then I can see what I can do. Because I am not using Raid-Helper myself. Thanks!

**Comment by Witnessthis** [comment]
The moment I wrote this issue I went back to double check that I hadn't missed any other way of exporting the raid composition from Raid-Helper. Turns out I had missed something.

This is an example of !print <Event ID>:

Name,Date,Time,Description,Created by,Link
addon test export string,24-12-2021,19:00,"test test",Dpscapped,https://discordapp.com/channels/<Removed rest of this string>

Role,Spec,Name,ID,Timestamp
Tank,Tank,Dpscapped,<ID>,2021-04-24T20:41:53
Tank,Tank,Zmaya,<ID>,2021-04-24T20:41:34

However! I would like to close this issue since I found out that one can use:

!signed <Event ID> list

And get the following:

Zmaya, Dpscapped,

Which is perfect for use with RIC already!

Sorry for the inconvenience.

**Comment by f90** [comment]
OK, then it definitely sounds like you should be using the list option so that you can use the normal list-based import that RIC understands already anyway!
No worries about the inconvenience, other people might stumble on the same problem and can find a solution here in the future. Have fun using the addon!
