### ISSUE TITLE
Members duplicated, not recognized as in guild

### ISSUE THREAD

**Issue by jrydh** [f90/RaidInviteClassic#15]
First time trying out the addon. After inviting, everyone on the roster was doubled - one showing as "Not in Guild" and one as "Not invited" - causing the addon to try to invite everyone again, spamming messages that they're in a group already.

![image](https://user-images.githubusercontent.com/50208/122457114-9a01cb00-cfae-11eb-97fb-fc9e8ad8f4ef.png)

**Comment by f90** [comment]
Hey, which WoW version are you playing on? Classic/TBC/Retail? Looks like it could be some simple issue with how names are handled now that I added support for realm names in character names

**Comment by f90** [comment]
So the addon is correctly inviting people on the roster, but then thinks they are still missing in the raid, correct?

**Comment by jrydh** [comment]
This is in TBC Classic, using the latest 2.3.0 version.

They all got invited, but the addon considered them all still missing and so kept attempting to invite again, yes. Made for some confused members. :)

**Comment by f90** [comment]
OK, thanks. How did you add them to the roster list? Via text import, add a guild member, manual player name entry?

**Comment by jrydh** [comment]
Text import with a long comma-separated string

**Comment by f90** [comment]
That long string contained the server names "Tina-Patchwerk" or just the character names themselves?

**Comment by jrydh** [comment]
Just the character names, so it was like "Alyanah,Bumpie,Darkmeister,Deveon ..."

**Comment by f90** [comment]
Do you still have this roster view with duplicate names? If so you can turn on "Show player realms" in the addon settings under GUI, to see whether they are treated as different people by the addon. That would explain why the addon still wants to invite them even though they are in the raid

**Comment by jrydh** [comment]
Did a fresh test. Realm names are correct and the same as far as I can see.

![image](https://user-images.githubusercontent.com/50208/122559877-2f00d480-d040-11eb-8df5-a8402d3acc49.png)

**Comment by jrydh** [comment]
Maybe this is it? GetRealmName() returns "Pyrewood Village", but you probably want GetNormalizedRealmName(), which returns "PyrewoodVillage".

**Comment by f90** [comment]
Yeah it's got to do with spaces in the realm name, which I don't have on my server so everything works perfectly there. I didn't know normalized realm names exist - I guess I should use them for this purpose?

**Comment by jrydh** [comment]
I modified line 206 in utils.lua to use GetNormalizedRealmName(), and I can verify that it now works as intended.

**Comment by f90** [comment]
Thanks, I am working on fixing it now, going through the whole code to make sure players everywhere are handled with charname-normalizedrealmname format. If you encounter more issues in the future just open up another issue please!

**Comment by f90** [comment]
v2.3.1 will be out in a few hours @jrydh 
Could you please update to that version and then tell me if this issue is fixed and everything seems fine regarding player name handling? Thanks!

**Comment by jrydh** [comment]
New version has fixed the issue. Thanks!
