### ISSUE TITLE
comma separated import

### ISSUE THREAD

**Issue by malagul** [f90/RaidInviteClassic#2]
There's a very popular Discord add-on for managing signups called `Raid-Helper` (https://raid-helper.com). This Discord bot allows event managers to export the signup list, but it comes as a comma separated list of names (all one line) instead of one-name-per-line. It'd be great if RaidInviteClassic supported both. Raid Helper has it's own in-game addon, but its far less featured than this one. 👍

**Comment by f90** [comment]
Hey, good idea. I already implemented this in v0.3.1 I think. Can you try updating to the latest version and importing a list to try it out?

**Comment by f90** [comment]
@malagul Is this issue resolved for you? I assume it is because you didn't reply again, and it's implemented in the current version to use comma, colon and newline characters to separate the names during text import.
