### ISSUE TITLE
Master Looter

### ISSUE THREAD

**Issue by bagzli** [f90/RaidInviteClassic#21]
This option never seems to work, when a raid is started I always have to manually set master loot option. I do notice it taking a few seconds to switch from party to raid and am wondering if that delay is the issue.

**Comment by f90** [comment]
Please try out version 2.4.2, should be fixed there, and report back here! Thanks

**Comment by f90** [comment]
Assuming this is fixed now due to lack of response. Otherwise reopen the issue!

**Comment by bagzli** [comment]
This seems to work for me now
