### ISSUE TITLE
Not accepting alt-codes/ special characters.

### ISSUE THREAD

**Issue by ghost** [f90/RaidInviteClassic#22]
Hello, it seems the last iteration has stopped the allowing of alt-codes. Names like ßaja, will show up aja. 

Thank you for you time and this great convenience addon.

**Comment by speaker** [comment]
Same issue

**Comment by f90** [comment]
Ah, I tried correcting names by putting the first letter into upper case, the rest into lower case. Unfortunately the method I used just removes special characters if it cannot convert them. Should be fixed now, can you check out version v2.4.4 and repot back if it works now? Thanks :)

**Comment by ghost** [comment]
Looks liek it works now. 
Thank you very much for getting on that so fast. 
You rock!
