### ISSUE TITLE
Errors in AV

### ISSUE THREAD

**Issue by bagzli** [f90/RaidInviteClassic#23]
When I joined AV I got the following error:

Message: Interface\AddOns\RaidInviteClassic\durability.lua:20: attempt to call local 'changed' (a boolean value)
Time: Wed Sep 15 16:24:08 2021
Count: 29
Stack: Interface\AddOns\RaidInviteClassic\durability.lua:20: attempt to call local 'changed' (a boolean value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: in function `changed'
[string "@Interface\AddOns\RaidInviteClassic\durability.lua"]:20: in function `func'
[string "@Interface\AddOns\RaidInviteClassic\libs\LibDurability\LibDurability.lua"]:68: in function <...idInviteClassic\libs\LibDurability\LibDurability.lua:51>

Locals: errMsg = "Interface\AddOns\RaidInviteClassic\durability.lua:20: attempt to call local 'changed' (a boolean value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:296
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by bagzli** [comment]
Happened Again in Eye of the Storm

Message: Interface\AddOns\RaidInviteClassic\durability.lua:20: attempt to call local 'changed' (a boolean value)
Time: Thu Sep 16 15:15:55 2021
Count: 3
Stack: Interface\AddOns\RaidInviteClassic\durability.lua:20: attempt to call local 'changed' (a boolean value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: in function `changed'
[string "@Interface\AddOns\RaidInviteClassic\durability.lua"]:20: in function `func'
[string "@Interface\AddOns\RaidInviteClassic\libs\LibDurability\LibDurability.lua"]:68: in function <...idInviteClassic\libs\LibDurability\LibDurability.lua:51>

Locals: errMsg = "Interface\AddOns\RaidInviteClassic\durability.lua:20: attempt to call local 'changed' (a boolean value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:296
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by f90** [comment]
Hey, please update to v2.4.5 and check whether the warnings are still there. They should be gone now. I simply disabled the warnings that popped up in case we receive durability info from a player whose name is not in our expected name format and would need to be changed to fit, so that info is something we can not work with anyway. 

Are the warnings now gone with the new version?

**Comment by bagzli** [comment]
my client doesn't show me there is an update, i'm still on 2.4.3 according to your ToC file

**Comment by f90** [comment]
Thats weird, maybe your Addon updater does not update the addon at the moment since you used some of my unreleased code? Here is the current file that the addon updaters are currently pulling:
https://www.curseforge.com/wow/addons/raid-invite-classic/files/3473083

**Comment by bagzli** [comment]
I am using curseforge

**Comment by bagzli** [comment]
Is there an easier way to check for what version I have that is not looking at TOC file?

**Comment by f90** [comment]
You can also type `/ric version` in the Wow ingame chat window. But it pretty much prints out the same as the version found in the TOC file. I just checked my Wowup addon updater and I can see v2.4.5 being offered right now. I also checked that the v2.4.5 zip file has the right version in the TOC file in it. So something must be wrong on your end with the addon updater setup. Maybe try removing the addon from your addon updater and readding it?

**Comment by bagzli** [comment]
That is strange. When I was on the page that shows all addons, it was showing no update. When I clicked on RIC then there was the update button and it let me update to latest version.

**Comment by bagzli** [comment]
I don't think I've seen the error as of late, if I see it again I'll update this ticket.
